# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20170421_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'profile_images'),
        ),
    ]
